import type { SuiteRunResult, ProblemResult } from "./types.js";

/**
 * Generates a shareable markdown report from suite run results.
 */
export function generateReport(results: SuiteRunResult[]): string {
  const lines: string[] = [];

  lines.push("# AgentMX Benchmark Report");
  lines.push("");
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push("");

  for (const suite of results) {
    lines.push(`## Suite: ${suite.suiteName}`);
    lines.push("");

    const agentNames = Array.from(suite.agentResults.keys());
    if (agentNames.length === 0) {
      lines.push("No agents were benchmarked.");
      lines.push("");
      continue;
    }

    // Summary table
    lines.push("### Summary");
    lines.push("");
    lines.push(summaryTable(suite));
    lines.push("");

    // Per-problem breakdown
    lines.push("### Per-Problem Results");
    lines.push("");

    const problemIds = new Set<string>();
    for (const results of suite.agentResults.values()) {
      for (const r of results) {
        problemIds.add(r.problemId);
      }
    }

    for (const problemId of problemIds) {
      const problemResults: ProblemResult[] = [];
      for (const agentResults of suite.agentResults.values()) {
        const r = agentResults.find((r) => r.problemId === problemId);
        if (r) problemResults.push(r);
      }

      if (problemResults.length === 0) continue;

      const problemName = problemResults[0].problemName;
      lines.push(`#### ${problemName}`);
      lines.push("");
      lines.push(problemTable(problemResults));
      lines.push("");
    }

    // Winner
    const winner = findWinner(suite);
    if (winner) {
      lines.push(`### Winner: ${winner.name}`);
      lines.push("");
      lines.push(
        `**${winner.name}** passed ${winner.passRate} of problems ` +
          `in ${(winner.totalTimeMs / 1000).toFixed(1)}s` +
          (winner.totalCost !== undefined
            ? ` ($${winner.totalCost.toFixed(4)})`
            : "") +
          "."
      );
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by [AgentMX](https://github.com/dimfeld/agentmux)*");

  return lines.join("\n");
}

function summaryTable(suite: SuiteRunResult): string {
  const lines: string[] = [];
  const agentNames = Array.from(suite.agentResults.keys());

  lines.push("| Agent | Pass Rate | Total Time | Total Cost |");
  lines.push("|-------|-----------|------------|------------|");

  for (const agentName of agentNames) {
    const results = suite.agentResults.get(agentName) ?? [];
    const passed = results.filter((r) => r.passed).length;
    const total = results.length;
    const passRate = total > 0 ? `${passed}/${total}` : "0/0";
    const totalTime = results.reduce((sum, r) => sum + r.timeMs, 0);
    const timeStr = (totalTime / 1000).toFixed(1) + "s";

    let costStr = "—";
    const costs = results.map((r) => r.cost).filter((c): c is number => c !== undefined);
    if (costs.length > 0) {
      costStr = "$" + costs.reduce((a, b) => a + b, 0).toFixed(4);
    }

    const displayName = results[0]?.displayName ?? agentName;
    const medal = passed === total && total > 0 ? " :trophy:" : "";

    lines.push(`| ${displayName}${medal} | ${passRate} | ${timeStr} | ${costStr} |`);
  }

  return lines.join("\n");
}

function problemTable(results: ProblemResult[]): string {
  const lines: string[] = [];

  lines.push("| Agent | Status | Tests | Time | Cost |");
  lines.push("|-------|--------|-------|------|------|");

  // Sort: passed first, then by time
  const sorted = [...results].sort((a, b) => {
    if (a.passed !== b.passed) return a.passed ? -1 : 1;
    return a.timeMs - b.timeMs;
  });

  for (const r of sorted) {
    const status = r.timedOut
      ? ":alarm_clock: Timeout"
      : r.error
        ? `:x: Error`
        : r.passed
          ? ":white_check_mark: Pass"
          : ":x: Fail";
    const tests = `${r.passedCount}/${r.totalCount}`;
    const time = (r.timeMs / 1000).toFixed(1) + "s";
    const cost = r.cost !== undefined ? "$" + r.cost.toFixed(4) : "—";

    lines.push(`| ${r.displayName} | ${status} | ${tests} | ${time} | ${cost} |`);
  }

  return lines.join("\n");
}

interface WinnerInfo {
  name: string;
  passRate: string;
  totalTimeMs: number;
  totalCost: number | undefined;
}

function findWinner(suite: SuiteRunResult): WinnerInfo | undefined {
  let best: WinnerInfo | undefined;
  let bestPassed = -1;
  let bestTime = Infinity;

  for (const [agentName, results] of suite.agentResults) {
    const passed = results.filter((r) => r.passed).length;
    const total = results.length;
    const totalTime = results.reduce((sum, r) => sum + r.timeMs, 0);

    const costs = results
      .map((r) => r.cost)
      .filter((c): c is number => c !== undefined);
    const totalCost = costs.length > 0 ? costs.reduce((a, b) => a + b, 0) : undefined;

    // Winner: most passes, then fastest
    if (passed > bestPassed || (passed === bestPassed && totalTime < bestTime)) {
      bestPassed = passed;
      bestTime = totalTime;
      best = {
        name: results[0]?.displayName ?? agentName,
        passRate: `${passed}/${total}`,
        totalTimeMs: totalTime,
        totalCost,
      };
    }
  }

  return best;
}
